### ISSUE TITLE
Changing in printing for Vector in Julia 1.6 will break the package.

### ISSUE THREAD

**Issue by KristofferC** [m-wells/AlignedBinaryFormat.jl#3]
In Julia 1.6, the printing of e.g. `Vector{Float64}` was changed from `Array{Float64, 1}` to `Vector{Float64}`. This broken the detection in 

https://github.com/m-wells/AlignedBinaryFormat.jl/blob/3ba8e3ea5e776300f1555324821eebbd34ac2d6b/src/read_write.jl#L69-L77

In general, it's not advisable to rely on the exact way a type is printed for e.g. serialization.

**Comment by m-wells** [comment]
Thanks for pointing this out.

**Comment by m-wells** [comment]
Fixed in version 0.6.1
